# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~>3.3'

# Specifying rails components to be able to omit unused actioncable
gem 'actionmailbox', '~> 8.0.2.1'
gem 'actionmailer', '~> 8.0.2.1'
gem 'actionpack', '~> 8.0.2.1'
gem 'actiontext', '~> 8.0.2.1'
gem 'actionview', '~> 8.0.2.1'
gem 'activejob', '~> 8.0.2.1'
gem 'activemodel', '~> 8.0.2.1'
gem 'active_model_serializers'
gem 'activerecord', '~> 8.0.2.1'
gem 'activerecord-session_store'
gem 'activestorage', '~> 8.0.2.1'
gem 'activesupport', '~> 8.0.2.1'
gem 'audited'
gem 'auto-session-timeout'
gem 'aws-sdk-cloudwatch'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'bundler', '>= 1.15.0'
gem 'dotenv-rails', groups: %i[development test]
gem 'fhir_models'
gem 'health_check'
gem 'jbuilder', '~> 2.7'
gem 'json-jwt', '>= 1.16.6'
gem 'kaminari'
gem 'lograge'
gem 'lookbook', '>= 2.2.1' # install lookbook so it can be deployed in lower environments.
gem 'luhnacy', '~> 0.2.1'
gem 'macaroons'
gem 'net-imap', '>= 0.5.8'
gem 'newrelic_rpm', '~> 8.10'
gem 'nokogiri', '>= 1.18.9'
gem 'omniauth_openid_connect'
gem 'omniauth-rails_csrf_protection'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 6.4.3'
gem 'rack', '>= 3.2.3'
gem 'rack-session', '>= 2.1.1'
gem 'railties', '~> 8.0.2.1'
gem 'rexml', '>= 3.4.2'
gem 'sassc-rails', '>= 2.1.2'
gem 'sinatra', '>= 4.2.0'
gem 'solid_queue', '~> 1.2'
gem 'truemail'
gem 'uglifier', '>= 1.3.0'
gem 'view_component', '~> 3.9'
gem 'webrick'
gem 'yard', '>= 0.9.36'

gem 'api_client', path: 'vendor/api_client'

group :production do
  gem 'pg-aws_rds_iam'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'bundler-audit'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'pry'
  gem 'pry-nav'
  gem 'rspec-rails'
  gem 'webmock'
end

group :development do
  gem 'rbnacl'
  gem 'rbnacl-libsodium'

  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false

  # Version 0.18 has a breaking change for sonarqube
  gem 'simplecov', '<= 0.17'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.1.0'
end

group :test do
  gem 'axe-core-capybara'
  gem 'axe-core-rspec'
  gem 'capybara'
  gem 'climate_control'
  gem 'fakefs', require: 'fakefs/safe'
  gem 'rails-controller-testing'
  gem 'selenium-webdriver'
  gem 'timecop'
  gem 'webdrivers'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
