# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
# Specifying rails components to be able to omit unused actioncable
gem 'actionmailbox', '~> 7.1.3.2'
gem 'actionmailer', '~> 7.1.3.2'
gem 'actionpack', '~> 7.1.3.2'
gem 'actiontext', '~> 7.1.3.2'
gem 'actionview', '~> 7.1.3.2'
gem 'activejob', '~> 7.1.3.2'
gem 'activemodel', '~> 7.1.3.2'
gem 'active_model_serializers'
gem 'activerecord', '~> 7.1.3.2'
gem 'activestorage', '~> 7.1.3.2'
gem 'activesupport', '~> 7.1.3.2'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'bundler', '>= 1.15.0'
gem 'devise'
gem 'devise-async'
gem 'devise-security'
gem 'dotenv-rails', groups: %i[development test]
gem 'fhir_client'
gem 'health_check'
gem 'jbuilder', '~> 2.7'
gem 'kaminari'
gem 'lograge'
gem 'lookbook', '>= 2.1.1' # install lookbook so it can be deployed in lower environments.
gem 'luhnacy', '~> 0.2.1'
gem 'macaroons'
gem 'newrelic_rpm', '~> 8.10'
gem 'omniauth_openid_connect'
gem 'omniauth-rails_csrf_protection'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 6.4.2'
gem 'rack', '~> 2.2.8.1'
gem 'railties', '~> 7.1.3.2'
gem 'redis', '~> 4.0'
gem 'redis-namespace'
gem 'rexml', '>= 3.2.5' # adding for CVE-2021-28965
gem 'sassc-rails', '>= 2.1.2'
gem 'sidekiq', '~> 7.1'
gem 'sidekiq_alive', '~> 2.1.5'
gem 'truemail'
gem 'uglifier', '>= 1.3.0'
gem 'view_component', '~> 3.9'

# < 1.13.2 has a vulnerability, and is required by other gems
gem 'nokogiri', '>= 1.16.2'

gem 'api_client', path: 'vendor/api_client'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'bundler-audit'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'pry'
  gem 'pry-nav'
  gem 'rspec-rails'
  gem 'webmock'
end

group :development do
  gem 'rbnacl'
  gem 'rbnacl-libsodium'

  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false

  gem 'simplecov'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'letter_opener'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'climate_control'
  gem 'fakefs', require: 'fakefs/safe'
  gem 'fakeredis'
  gem 'rails-controller-testing'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
