x-dd-config:
  environment: &dd-default-env
    DD_AGENT_HOST: datadog-agent
    DD_ENV: local-dev
    DD_VERSION: 0.4.0-SNAPSHOT
    DD_PROFILING_ENABLED: true
    DD_TRACE_OTEL_ENABLED: true
    DD_INSTRUMENTATION_TELEMETRY_ENABLED: false
    DD_TRACE_SAMPLING_RULES: |
      [
        {"resource":"GET /healthcheck","sample_rate":0.0},
        {"resource":"GET /v1/version","sample_rate":0.0},
        {"resource":"GET /v1/fhir/metadata","sample_rate":0.0},
        {"resource":"GET /api/v1/version","sample_rate":0.0},
        {"resource":"GET GET /ping","sample_rate":0.0}
      ]

services:
  db:
    image: artifactory.cloud.cms.gov/docker/postgres:16.4
    command: postgres -c 'max_connections=250'
    environment:
      - POSTGRES_MULTIPLE_DATABASES=dpc_attribution,dpc_queue,dpc_auth,dpc_consent,dpc-website_development,bcda,dpc-portal_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dpc-safe
    volumes:
      # Mount database startup script, which automatically creates new databases
      # based on the POSTGRES_MULTIPLE_DATABASES variable above.
      - ./docker/postgres:/docker-entrypoint-initdb.d
      # Mount persistent volume to ensure data is not erased across containers.
      - pgdata16:/var/lib/postgresql/data
      - ./tmp:/var/tmp
      - ./scripts:/scripts
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER}"
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5

  datadog-agent:
    image: public.ecr.aws/datadog/agent:7.50.0
    container_name: datadog-agent
    env_file:
      - ops/config/decrypted/local.env
    environment:
      - DD_SITE=ddog-gov.com
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_HOSTNAME=local-dev

  aggregation:
    image: dpc-aggregation:latest
    platform: linux/arm64
    ports:
      - "9901:9901"
    env_file:
      - ops/config/decrypted/local.env
    environment:
      <<: *dd-default-env
      ENV: local
      USE_BFD_MOCK: ${USE_BFD_MOCK:-true}
      EMIT_AWS_METRICS: ${EMIT_AWS_METRICS:-false}
      JACOCO: ${REPORT_COVERAGE:-}
      DEBUG_MODE: ${DEBUG_MODE:-false}
      DD_SERVICE: dpc-local-aggregation
    depends_on:
      db:
        condition: service_healthy
      datadog-agent:
        condition: service_started
    volumes:
      - export-volume:/app/data
      - ./jacocoReport/dpc-aggregation:/jacoco-report
    healthcheck:
      test: curl --fail http://localhost:9901/healthcheck || exit 1
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 10

  attribution:
    image: dpc-attribution:latest
    platform: linux/arm64
    depends_on:
      db:
        condition: service_healthy
      datadog-agent:
        condition: service_started
    env_file:
      - ops/config/decrypted/local.env
    environment:
      <<: *dd-default-env
      ENV: local
      JACOCO: ${REPORT_COVERAGE:-}
      DEBUG_MODE: ${DEBUG_MODE:-false}
      DD_SERVICE: dpc-local-attribution
    ports:
      - "3500:8080"
      - "9902:9902"
    volumes:
      - ./jacocoReport/dpc-attribution:/jacoco-report
    healthcheck:
      test: curl --fail http://localhost:9902/healthcheck || exit 1
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 10

  api:
    image: dpc-api:latest
    platform: linux/arm64
    ports:
      - "3002:3002"
      - "9903:9900"
    env_file:
      - ops/config/decrypted/local.env
    environment:
      <<: *dd-default-env
      ENV: local
      JACOCO: ${REPORT_COVERAGE:-}
      EXPORT_PATH: /app/data
      AUTH_DISABLED: ${AUTH_DISABLED:-false}
      DEBUG_MODE: ${DEBUG_MODE:-false}
      USE_BFD_MOCK: ${USE_BFD_MOCK:-true}
      DD_AGENT_HOST: datadog-agent
    depends_on:
      attribution:
        condition: service_healthy
      datadog-agent:
        condition: service_started
    volumes:
      - export-volume:/app/data
      - ./jacocoReport/dpc-api:/jacoco-report
    healthcheck:
      test: curl --fail http://localhost:9900/healthcheck || exit 1
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 10

  tests:
    image: maven:3.9.9-amazoncorretto-17
    platform: linux/arm64
    env_file:
      - ops/config/decrypted/local.env
    volumes:
      - export-volume:/tmp
      - ./:/usr/src/mymaven
    working_dir: /usr/src/mymaven
    command: sh -c "mvn verify -Pintegration-tests -am -ntp -Djib.skip=true"
    network_mode: host

volumes:
  pgdata16:
  export-volume:
    driver: local
    driver_opts:
      type: none
      device: /tmp
      o: bind
