#!/bin/bash
set -Ee

function _finally {
  # don't shut it down if running on ci
  if [ "$ENV" != 'github-ci' ]; then
    echo "SHUTTING EVERYTHING DOWN"
    docker compose -p client-integration-app down
    docker volume rm client-integration-app_pgdata16
  fi
}

trap _finally EXIT

# Build the application
# mvn clean compile -Perror-prone -B -V -ntp -T 4 -DskipTests
# mvn package -Pci -ntp -T 4 -DskipTests

echo "Starting api server for client integration tests"
JACOCO=false USE_BFD_MOCK=true docker compose -p client-integration-app up api --wait

export GOLDEN_MACAROON=$(curl -X POST http://localhost:9903/tasks/generate-token)

echo "Starting end-to-end tests"
SKIP_SIMPLE_COV=true docker compose -p client-integration-app -f docker-compose.yml -f docker-compose.portals.yml run --entrypoint "bundle exec rspec --tag type:integration" dpc_client

# Wait for Jacoco to finish writing the output files
docker compose -p client-integration-app down -t 60
