# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.6'

# Anchored versions, do not bump without testing
# Specifying rails components to be able to omit unused actioncable
gem 'actionmailbox', '~> 7.0.5.1'
gem 'actionmailer', '~> 7.0.5.1'
gem 'actionpack', '~> 7.0.5.1'
gem 'actiontext', '~> 7.0.5.1'
gem 'actionview', '~> 7.0.5.1'
gem 'activejob', '~> 7.0.5.1'
gem 'activemodel', '~> 7.0.5.1'
gem 'activerecord', '~> 7.0.5.1'
gem 'activestorage', '~> 7.0.5.1'
gem 'activesupport', '~> 7.0.5.1'
gem 'railties', '~> 7.0.5.1'
gem 'bundler', '>= 1.15.0'
gem 'sprockets-rails', '>= 3.4.2'
gem 'puma', '~> 5.6.4'
gem 'redis', '~> 4.0'
gem 'coffee-rails', '~> 5.0', '>= 5.0.0'
gem 'kramdown', '~> 2.3', '>= 2.3.1'
gem 'luhnacy', '~> 0.2.1'
gem 'sidekiq', '~> 7.0', '>= 7.0.8'
gem 'newrelic_rpm', '~> 8.10'
gem 'rexml', '>= 3.2.5' # adding for CVE-2021-28965
gem 'bootsnap', '>= 1.1.0', require: false
gem 'sassc-rails', '>= 2.1.2'
gem 'uglifier', '>= 1.3.0'
gem 'pg', '>= 0.18', '< 2.0'
gem 'devise', '>= 4.8.1'
gem 'devise-async', '>= 1.0.0'
gem 'devise-security', '>= 0.17.0'
gem 'truemail'
gem 'health_check', '>= 3.1.0'
gem 'fhir_client', '>= 5.0.3'
gem 'sidekiq_alive', '~> 2.1.5'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'kaminari', '>= 1.2.2'
gem 'active_model_serializers', '>= 0.10.13'
gem 'macaroons'
gem 'lograge', '>= 0.13.0'
gem 'redis-namespace'
gem 'bootstrap-table-rails'

# < 1.13.2 has a vulnerability, and is required by other gems
gem 'nokogiri', '>= 1.13.10'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry'
  gem 'pry-nav'
  gem 'rspec-rails', '>= 5.1.2'
  gem 'database_cleaner'
  gem 'capybara', '>= 3.37.1'
  gem 'factory_bot_rails', '>= 6.2.0'
  gem 'faker'
  # Version 0.18 has a breaking change for sonarqube
  gem 'simplecov', '<= 0.17'
  gem 'vcr'
  gem 'webmock', '>= 3.13.0'
  gem 'bundler-audit'
  gem 'brakeman'
  gem 'dotenv-rails', '>= 2.8.1'
end

group :test do
  gem 'selenium-webdriver'
  gem 'climate_control'
  gem 'rails-controller-testing', '>= 1.0.5'
  gem 'fakefs', require: 'fakefs/safe'
  gem 'fakeredis'
end

group :development do
  gem 'web-console', '>= 4.2.0'
  gem 'listen', '>= 3.0.5', '< 3.3'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'rubocop', '>= 1.12.0', require: false
  gem 'rubocop-performance', '>= 1.10.2', require: false

  gem 'letter_opener', '>= 1.7.0'

  gem 'letter_opener_web', '~> 2.0', '>= 2.0.0'
end
