# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

gem 'rails', '~> 5.2.3'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 4.3'
gem 'sassc-rails', '>= 2.1.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 5.0'
gem 'jbuilder', '~> 2.5'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'rouge-rails'
gem 'kramdown', '~> 2.1'

gem 'jquery-rails'
gem 'devise'
gem 'brakeman'
gem 'health_check'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry'
  gem 'pry-nav'

  gem 'rspec-rails'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'simplecov', require: false
  gem 'vcr'
  gem 'webmock'

  gem 'bundler-audit'
end

group :test do
  gem 'selenium-webdriver'
  gem 'climate_control'
  gem 'rails-controller-testing'
  gem 'fakefs', require: 'fakefs/safe'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.3'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false

  gem 'letter_opener'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'delayed_job_active_record'
gem 'daemons'
gem 'omniauth-github'
gem 'omniauth-rails_csrf_protection', '~> 0.1'
gem 'octokit'
gem 'kaminari'
gem 'active_model_serializers'
gem 'macaroons'
gem 'newrelic_rpm', '~> 6.8'
gem 'fhir_client'
