
FROM golang:1.15-buster

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

RUN go get -u github.com/securego/gosec/cmd/gosec
RUN go get -u gotest.tools/gotestsum

WORKDIR dpc-attribution
COPY ./dpc-go/dpc-attribution .