
FROM golang:1.16.7-buster

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

RUN go get -u github.com/xo/usql
RUN go get -u github.com/securego/gosec/cmd/gosec
RUN go get -u gotest.tools/gotestsum
RUN go get -u github.com/tsenart/vegeta
RUN go get -u -d github.com/golang-migrate/migrate/cmd/migrate; \
    cd $GOPATH/src/github.com/golang-migrate/migrate/cmd/migrate; \
    git checkout v4.10.0; \
    go build -tags 'postgres' -ldflags="-X main.Version=$(git describe --tags)" -o $GOPATH/bin/migrate github.com/golang-migrate/migrate/v4/cmd/migrate

WORKDIR /go/src/github.com/CMSgov/dpc-app
COPY . .

WORKDIR /go/src/github.com/CMSgov/dpc-app
ENTRYPOINT []