# See: https://github.com/corretto/corretto-docker/blob/a2a619f2ff274d58df109c775ae79acc7b8605a2/17/jdk/alpine/3.20/Dockerfile
FROM amazoncorretto:17-alpine-jdk

# Install additional packages used across DPC images
RUN  apk update && apk add --no-cache aws-cli && apk add --no-cache curl

# Use the corretto:17 default command/entrypoint
CMD ["jshell"]
