source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
# Specifying rails components to be able to omit unused actioncable
gem 'actionmailbox', '>= 7.0.3.1'
gem 'actionmailer', '>= 7.0.3.1'
gem 'actionpack', '>= 7.0.3.1'
gem 'actiontext', '>= 7.0.3.1'
gem 'actionview', '>= 7.0.3.1'
gem 'activejob', '>= 6.0.5.1'
gem 'activemodel', '>= 6.0.5.1'
gem 'activerecord', '>= 6.0.5.1'
gem 'activestorage', '>= 6.0.5.1'
gem 'activesupport', '>= 6.0.5.1'
gem 'bundler', '>= 1.15.0'
gem 'railties', '>= 6.0.5.1'
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '>= 5.6.4'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6.0.0'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 5.4', '>= 5.4.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'
gem 'redis-namespace'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'
gem 'sidekiq', '>= 6.4'
gem 'sidekiq_alive'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false
gem 'health_check', '>= 3.1.0'

gem 'omniauth-rails_csrf_protection', '~> 0.1', '>= 0.1.2'
gem 'devise', '>= 4.8.0'
gem 'devise-async', '>= 1.0.0'
gem 'devise-security', '>= 0.16.0'
gem 'omniauth-github'
gem 'omniauth-oktaoauth'
gem 'octokit' # can be removed once we move past github omniauth

gem 'truemail'
# < 1.13.2 has a vulnerability, and is required by other gems
gem 'nokogiri', '>= 1.13.4'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry'
  gem 'pry-nav'
  gem 'rspec-rails', '>= 5.0.1'
  gem 'database_cleaner'
  gem 'capybara', '>= 3.35.3'
  gem 'factory_bot_rails', '>= 6.2.0'
  gem 'faker'
  gem 'vcr'
  gem 'webmock'
  gem 'dotenv-rails', '>= 2.7.6'
  gem 'bundler-audit'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'simplecov', '<= 0.17'
  gem 'letter_opener_web', '~> 2.0'
  gem 'letter_opener'
end

group :test do
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
  gem 'climate_control'
  gem 'rails-controller-testing', '>= 1.0.5'
  gem 'fakeredis'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
