source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in api_client.gemspec.
gemspec

gem 'sqlite3', git: "https://github.com/sparklemotion/sqlite3-ruby"
gem "sprockets-rails"
gem 'macaroons'
gem 'fhir_client'
gem 'active_model_serializers'
gem 'rubocop'
gem 'webmock'
# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
