# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in api_client.gemspec.
gemspec

gem 'active_model_serializers'
gem 'fhir_models'
gem 'macaroons'
gem 'nokogiri', '>= 1.18.3'
gem 'oauth2'
gem 'rspec-rails'
gem 'rubocop'
gem 'simplecov'
gem 'sprockets-rails'
gem 'sqlite3', git: 'https://github.com/sparklemotion/sqlite3-ruby'
gem 'webmock'
# Start debugger with binding.b [https://github.com/ruby/debug]
# gem 'debug', '>= 1.0.0'
