source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

gem 'rails', '~> 6.1.4', '>= 6.1.4.1'
gem 'pg', '~> 1.1'
gem 'puma', '>= 5.3.1'
gem 'redis', '~> 4.0'
gem 'sass-rails', '>= 6.0.0'
gem 'webpacker', '~> 5.4', '>= 5.4.0'
gem 'sidekiq', '~> 6.1'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.7'
gem 'newrelic_rpm', '~> 6.10'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'devise', '>= 4.8.0'
gem 'devise_invitable', '~> 2.0.5'
gem 'devise-security', '>= 0.16.0'
gem 'health_check', '>= 3.1.0'
gem 'truemail'
gem 'sidekiq_alive'
gem 'redis-namespace'
gem 'lograge', '>= 0.11.2'
gem 'luhnacy', '~> 0.2.1'
# < 1.12.5 has a vulnerability, and is required by other gems
gem 'nokogiri', '>= 1.12.5'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry'
  gem 'pry-nav'
  gem 'rspec-rails', '>= 5.0.1'
  gem 'database_cleaner'
  gem 'capybara', '>= 3.35.3'
  gem 'factory_bot_rails', '>= 6.2.0'
  gem 'faker'
  gem 'vcr'
  gem 'webmock'
  gem 'dotenv-rails', '>= 2.7.6'
  gem 'bundler-audit'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  gem 'listen', '~> 3.3'
  gem 'letter_opener_web', '~> 1.4', '>= 1.4.0'

  gem 'simplecov', '<= 0.17'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'letter_opener'
end

group :test do
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
  gem 'fakeredis'
  gem 'rails-controller-testing', '>= 1.0.5'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
