source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.4', '>= 6.0.4.1'
gem 'dotenv-rails', '>= 2.7.6', groups: [:development, :test]
gem 'puma', '~> 4.3.8'
gem 'redis', '~> 4.0'
gem 'luhnacy', '~> 0.2.1'
gem 'omniauth-rails_csrf_protection', '~> 0.1', '>= 0.1.2'
gem 'sidekiq', '~> 6.1'
gem 'webpacker', '~> 4.3', '>= 4.3.0'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.7'
gem 'newrelic_rpm', '~> 6.10'
gem 'rexml', '>= 3.2.5' # adding for CVE-2021-28965
gem 'bootsnap', '>= 1.4.2', require: false
gem 'sassc-rails', '>= 2.1.2'
gem 'uglifier', '>= 1.3.0'
gem 'pg', '>= 0.18', '< 2.0'
gem 'devise', '>= 4.8.0'
gem 'devise-async', '>= 1.0.0'
gem 'devise-security', '>= 0.16.0'
gem 'health_check', '>= 3.0.0'
gem 'omniauth-github'
gem 'omniauth-oktaoauth'
gem 'octokit' # can be removed once we move past github omniauth
gem 'fhir_client'
gem 'sidekiq_alive'
gem 'redis-namespace'
gem 'kaminari'
gem 'active_model_serializers', '>= 0.10.12'
gem 'lograge', '>= 0.11.2'
gem 'macaroons'
gem 'truemail'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry'
  gem 'pry-nav'
  gem 'rspec-rails', '>= 5.0.1'
  gem 'factory_bot_rails', '>= 6.2.0'
  gem 'database_cleaner'
  gem 'bundler-audit'
  gem 'webmock'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  gem 'listen', '~> 3.2'

  gem 'rbnacl-libsodium'
  gem 'rbnacl'

  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false

  gem 'simplecov', '<= 0.17'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'letter_opener'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'climate_control'
  gem 'rails-controller-testing', '>= 1.0.5'
  gem 'selenium-webdriver'
  gem 'fakefs', require: 'fakefs/safe'
  gem 'fakeredis'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
