FROM golang:1.18-buster

ENV GO111MODULE=on

# Download all dependencies
COPY ../../../go.mod ../../../go.sum ./

RUN go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.0
RUN go install github.com/securego/gosec/v2/cmd/gosec@v2.12.0
RUN go install gotest.tools/gotestsum@v1.8.1

WORKDIR dpc-attribution
COPY . .