FROM golang:1.15-alpine3.12 AS builder
RUN apk add --no-cache git
WORKDIR /app/dpc-attribution
COPY src/ .
COPY configs ../configs
RUN go build  -o ./bin/attribution .

FROM golang:1.15-alpine3.12
RUN apk update upgrade
RUN apk --no-cache add ca-certificates aws-cli curl
WORKDIR /app/dpc-attribution
COPY --from=builder /app/configs ../configs
COPY --from=builder /app/dpc-attribution/bin/attribution ./bin/attribution
CMD ["./bin/attribution"]


