shared:
  port: 443
  scheme: 'https'
development: &development
  login_dot_gov:
    host: <%= ENV['IDP_LOGIN_DOT_GOV_HOST'] %>
    identifier: '<%= "urn:gov:cms:openidconnect.profiles:sp:sso:cms:dpc:#{ENV['ENV']}" %>'
    user_info_endpoint: <%= "https://#{ENV['IDP_LOGIN_DOT_GOV_HOST']}/api/openid_connect/userinfo" %>
    log_out_path: '/openid_connect/logout'
    token_expiration_interval: 300
    redirect_path: '/auth/login_dot_gov/callback'
    acr_values: 'http://idmanagement.gov/ns/assurance/ial/2'
    authorize_scope: 'openid email all_emails profile social_security_number'
    authorization_endpoint: <%= "https://#{ENV['IDP_LOGIN_DOT_GOV_HOST']}/openid_connect/authorize" %>
    token_endpoint: <%= "https://#{ENV['IDP_LOGIN_DOT_GOV_HOST']}/api/openid_connect/token" %>
    jwks_uri: <%= "https://#{ENV['IDP_LOGIN_DOT_GOV_HOST']}/api/openid_connect/certs" %>

  id_me:
    host: <%= ENV['IDP_ID_ME_HOST'] %>
    identifier: <%= ENV['IDP_ID_ME_CLIENT_ID'] %>
    client_secret: <%= ENV['IDP_ID_ME_CLIENT_SECRET'] %>
    authorization_endpoint: <%= "https://#{ENV['IDP_ID_ME_HOST']}/oauth/authorize" %>
    token_endpoint: <%= "https://#{ENV['IDP_ID_ME_HOST']}/oauth/token" %>
    user_info_endpoint: <%= "https://#{ENV['IDP_ID_ME_HOST']}/api/public/v3/userinfo" %>
    jwks_uri: <%= "https://#{ENV['IDP_ID_ME_HOST']}/oidc/.well-known/jwks" %> 
    redirect_path: '/auth/id_me/callback'
    authorize_scope: 'openid http://idmanagement.gov/ns/assurance/ial/2/aal/2'
    log_out_path: '/oauth/logout'
    token_expiration_interval: 300

  clear:
    host: <%= ENV['CLEAR_IDP_HOST'] %>
    identifier: <%= ENV['CLEAR_IDP_CLIENT_ID'] %>
    client_secret: <%= ENV['CLEAR_IDP_CLIENT_SECRET'] %>
    authorization_endpoint: <%= "https://#{ENV['CLEAR_IDP_HOST']}/integrations/oauth2/auth" %>
    token_endpoint: <%= "https://#{ENV['CLEAR_IDP_HOST']}/integrations/oauth2/token" %>
    user_info_endpoint: <%= "https://#{ENV['CLEAR_IDP_HOST']}/integrations/userinfo" %>
    jwks_uri: <%= "https://#{ENV['CLEAR_IDP_HOST']}/integrations/.well-known/jwks.json" %>
    redirect_path: '/auth/clear/callback'
    authorize_scope: 'openid'
    log_out_path: '/integrations/oauth2/sessions/logout'
    token_expiration_interval: 300

local:
  <<: *development

test:
  <<: *development

production:
  <<: *development
