shared:
  port: 443
  scheme: 'https'
development: &development
  login_dot_gov:
    host: <%= ENV['IDP_LOGIN_DOT_GOV_HOST'] %>
    identifier: '<%= "urn:gov:cms:openidconnect.profiles:sp:sso:cms:dpc:#{ENV['ENV']}" %>'
    user_info_endpoint: <%= "https://#{ENV['IDP_ID_ME_HOST']}/api/openid_connect/userinfo" %>
    log_out_path: '/openid_connect/logout?client_id=%{client_id}&post_logout_redirect_uri=%{redirect_uri}&state=%{state}'
    token_expiration_interval: 300

    redirect_path: '/auth/login_dot_gov/callback'
    authorization_endpoint: <%= "https://#{ENV['IDP_LOGIN_DOT_GOV_HOST']}/openid_connect/authorize" %>
    token_endpoint: <%= "https://#{ENV['IDP_LOGIN_DOT_GOV_HOST']}/api/openid_connect/token" %>
    user_info_endpoint: <%= "https://#{ENV['IDP_ID_IDP_LOGIN_DOT_GOV_HOSTME_HOST']}/api/openid_connect/userinfo" %>
    jwks_uri: <%= "https://#{ENV['IDP_LOGIN_DOT_GOV_HOST']}/api/openid_connect/certs" %> 
    
  id_me:
    host: <%= ENV['IDP_ID_ME_HOST'] %>
    identifier: <%= ENV['IDP_ID_ME_CLIENT_ID'] %>
    client_secret: <%= ENV['IDP_ID_ME_CLIENT_SECRET'] %>
    authorization_endpoint: <%= "https://#{ENV['IDP_ID_ME_HOST']}/oauth/authorize" %>
    token_endpoint: <%= "https://#{ENV['IDP_ID_ME_HOST']}/oauth/token" %>
    user_info_endpoint: <%= "https://#{ENV['IDP_ID_ME_HOST']}/api/public/v3/userinfo" %>
    jwks_uri: <%= "https://#{ENV['IDP_ID_ME_HOST']}/oidc/.well-known/jwks" %> 
    redirect_path: '/auth/id_me/callback'
    log_out_path: '/oauth/logout?client_id=%{client_id}&redirect_uri=%{redirect_uri}'
    token_expiration_interval: 300

local:
  <<: *development

test:
  <<: *development
