FROM golang:1.17.5-buster

ENV GO111MODULE=on

RUN go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.0
RUN go get -u github.com/securego/gosec/cmd/gosec
RUN go get -u gotest.tools/gotestsum

WORKDIR dpc-api
COPY . .