FROM golang:1.15-alpine3.12 AS builder
RUN apk add --no-cache git
WORKDIR /app/dpc-api
COPY src/ .
COPY configs ../configs
COPY swaggerui ../swaggerui
RUN go build  -o ./bin/api .

FROM golang:1.15-alpine3.12
RUN apk update upgrade
RUN apk --no-cache add ca-certificates aws-cli curl
WORKDIR /app/dpc-api
COPY --from=builder /app/configs ../configs
COPY --from=builder /app/swaggerui ../swaggerui
COPY --from=builder /app/dpc-api/bin/api ./bin/api
CMD ["./bin/api"]
