FROM golang:1.15-alpine3.12

RUN apk add --no-cache git

# Set the Current Working Directory inside the container
WORKDIR /app/dpc-api

# We want to populate the module cache based on the go.{mod,sum} files.
COPY src/ .
COPY configs ../configs
COPY swaggerui ../swaggerui

# Build the Go app
RUN go build  -o ./bin/api .

# This container exposes port 8080 to the outside world
EXPOSE 8080

# Run the binary program produced by `go install`
CMD ["./bin/api"]