#ENC[AES256_GCM,data:pOUXpOwt62d4wtXd3fVMfHxlHELE6Elzgdbw6aX5JtWWkWNBlrR/T8QDHPF3RD7EItzhhIrovrF54XlqRZQMoZhrNfyyeJPqj8c5vNeuCQNX/Lauk0AUGw==,iv:r/Yy1JF/tGqveO1B+bGckszQwUGs9bQO08Zfbt43Wc4=,tag:eEghxxNdEw21nGyA9/JQKQ==,type:comment]
#ENC[AES256_GCM,data:hWuD+XMQo29F1GJ9V1G9ogf5ucpprR9M3ShkLkufIQKs9UQ=,iv:LCJbBd21BCaQS3BdBm6Pcf8jeA1Eb65CJP7UYGS8EJ0=,tag:XSJpz0wm3zsxmVSfJ8I/8A==,type:comment]
/dpc/prod/web-portal/idp_id_me_host: ""
/dpc/prod/web-portal/idp_id_me_client_id: ""
/dpc/prod/web-portal/idp_id_me_client_secret: ""
/dpc/prod/web-portal/clear_idp_host: ""
/dpc/prod/web-portal/clear_idp_client_id: ""
/dpc/prod/web-portal/clear_idp_client_secret: ""
/dpc/prod/web-portal/idp_login_dot_gov_host: ""
/dpc/prod/web-portal/login_dot_gov_client_private_key: ""
sops:
  kms:
    - arn: arn:aws:kms:us-east-1:${ACCOUNT_ID}:alias/dpc-prod
      created_at: "2026-02-24T19:46:01Z"
      enc: AQICAHhNpEKO9SHE//bg9rfjqqIKCtODlTsy5G1GVvT0FfmHagEhZuwrrACDbLCw6TXIzvE6AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNqEr8VcOEr+8TMznAgEQgDuRH0h5SEvcm+FYYpwqycm3ORFOAmOezzPgF+NGXiK2EvNNErMOCYp28xEbERFNAzfvtf3Xp3I3N0geXw==
      aws_profile: ""
    - arn: arn:aws:kms:us-west-2:${ACCOUNT_ID}:alias/dpc-prod
      created_at: "2026-02-24T19:46:11Z"
      enc: AQICAHjgOVH6vKv/vT7Ugq8lVNuajbWIVNXc6apsO+9oPWq1jAGEhxlmXbPXxR2nk2cB8eCkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvlTuL7odaUh4qup0AgEQgDuhJYKr7WLjalsnY2TrVfM+a+xLzuB3e8kEEzp5ITaH23vo5UVZEbIchxv4NBczKc0X3adhs9wBKdNIaQ==
      aws_profile: ""
  unencrypted_regex: /nonsensitive/
  version: 3.12.1
