#ENC[AES256_GCM,data:CA2IVf6dZ2wt5LoFy3e5q+OjY9vrND8gmvvof7NMG+x5fv6+rwLf8WV7FjoQa0JLR9cMjW2qzWZ9IB61U5WWhfX+7wxEMMOXdV97XgLUJrvAKNc=,iv:kQ2HFyc3dbHW2gcF60RMvvu6OLHgj97D7eeqf3AUa0E=,tag:BzzkUBdwffcaxu6adRiTHw==,type:comment]
/dpc/prod/example_sops_key: ""
sops:
  kms:
    - arn: arn:aws:kms:us-east-1:${ACCOUNT_ID}:alias/dpc-prod
      created_at: "2026-02-24T19:46:01Z"
      enc: AQICAHhNpEKO9SHE//bg9rfjqqIKCtODlTsy5G1GVvT0FfmHagEhZuwrrACDbLCw6TXIzvE6AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNqEr8VcOEr+8TMznAgEQgDuRH0h5SEvcm+FYYpwqycm3ORFOAmOezzPgF+NGXiK2EvNNErMOCYp28xEbERFNAzfvtf3Xp3I3N0geXw==
      aws_profile: ""
    - arn: arn:aws:kms:us-west-2:${ACCOUNT_ID}:alias/dpc-prod
      created_at: "2026-02-24T19:46:11Z"
      enc: AQICAHjgOVH6vKv/vT7Ugq8lVNuajbWIVNXc6apsO+9oPWq1jAGEhxlmXbPXxR2nk2cB8eCkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvlTuL7odaUh4qup0AgEQgDuhJYKr7WLjalsnY2TrVfM+a+xLzuB3e8kEEzp5ITaH23vo5UVZEbIchxv4NBczKc0X3adhs9wBKdNIaQ==
      aws_profile: ""
  unencrypted_regex: /nonsensitive/
  version: 3.12.1
