package gov.cms.dpc.api.resources;

import io.swagger.annotations.ApiKeyAuthDefinition;
import io.swagger.annotations.SecurityDefinition;
import io.swagger.annotations.SwaggerDefinition;

@SwaggerDefinition(
        securityDefinition = @SecurityDefinition(
                apiKeyAuthDefinitions = {
                        @ApiKeyAuthDefinition(key = "access_token", name = "Authorization", in = ApiKeyAuthDefinition.ApiKeyLocation.HEADER, description = "Access tokens are generated by following the SMART Backend Services Authentication guide, outlined in the documentation." +
                                "<p>Ensure that your access_token is prefixed with `Bearer `")
                }
        )
)
class SecurityDefinitions {
}
