name: utility-check-healthy

on:
  workflow_call:
    inputs:
      env:
        description: AWS environment to check
        required: true
        type: 'string'
        default: 'dev'

jobs:
  wait-for-services:
    name: Wait for services to be healthy
    runs-on: >-
      codebuild-dpc-app${{
        contains(fromJSON('["prod", "sandbox"]'), inputs.env) && '-prod' || '-non-prod'
      }}-${{ github.run_id }}-${{ github.run_attempt }}
    strategy:
      matrix:
        include:
          - service: api
            script_params: api-1 api frontend v9
            skip: false
          - service: attribution
            script_params: attribution attribution backend v9
            skip: false
          - service: aggregation
            script_params: none aggregation backend v9
            skip: false
          - service: web
            script_params: web-v2-1 web frontend v9
            skip: ${{ inputs.env == 'prod' }}
          - service: admin
            script_params: web-admin-1 web-admin frontend v9
            skip: ${{ inputs.env == 'prod' }}
          - service: web-portal
            script_params: web-portal-1 web-portal frontend v9
            skip: ${{ inputs.env == 'prod' || inputs.env == 'sandbox' }}
          - service: async-portal
            script_params: none async-portal frontend v9
            skip: ${{ inputs.env == 'prod' || inputs.env == 'sandbox' }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.3.0
        with:
          path: dpc-app
      - name: AWS Credentials (non-prod)
        if: ${{ inputs.env == 'dev' || inputs.env == 'test' }}
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.NON_PROD_ACCOUNT_ID }}:role/delegatedadmin/developer/dpc-${{ inputs.env }}-github-actions
      - name: AWS Credentials (prod)
        if: ${{ inputs.env == 'sandbox' || inputs.env == 'prod' }}
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.PROD_ACCOUNT_ID }}:role/delegatedadmin/developer/dpc-${{ inputs.env }}-github-actions
      - name: Check Service
        run: |
          ./dpc-app/scripts/check-deployment-status.sh ${{ inputs.env }} ${{ matrix.script_params }} ${{ matrix.skip }}
