name: "DPC CI Workflow"

on:
  pull_request:
    paths:
      - .github/workflows/ci-workflow.yml
      - dpc-admin/**
      - dpc-aggregation/**
      - dpc-api/**
      - dpc-attribution/**
      - dpc-bluebutton/**
      - dpc-common/**
      - dpc-macaroons/**
      - dpc-portal/**
      - dpc-queue/**
      - dpc-smoketest/**
      - dpc-test.sh
      - dpc-testing/**
      - dpc-web/**
      - engines/**
      - pom.xml
      - src/**
  workflow_dispatch: # Allow manual trigger

permissions:
  id-token: write
  contents: read

concurrency:
  group: ci-workflow-${{ github.ref }}
  cancel-in-progress: true

env:
  VAULT_PW: ${{ secrets.VAULT_PW }}
  DPC_CA_CERT: ${{ secrets.DPC_CA_CERT }}
  ENV: "github-ci"

jobs:
  build-dpc-api-client:
    name: "Build and Test DPC Client"
    runs-on: codebuild-dpc-app-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - name: Assert Ownership
        run: sudo chmod -R 777 .
      - name: "Checkout code"
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Cleanup Runner
        run: ./scripts/cleanup-docker.sh
      - name: Install docker compose manually
        run: |
          mkdir -p /usr/local/lib/docker/cli-plugins
          curl -SL https://github.com/docker/compose/releases/download/v2.32.4/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
          chown root:root /usr/local/lib/docker/cli-plugins/docker-compose
          chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
      - name: "Client Unit Tests"
        run: |
          make ci-api-client
      - name: "Set up Python and install Ansible"
        run: |
          sudo dnf -y install python3 python3-pip
          pip install ansible
      - name: "Set up JDK 17"
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: "17"
          distribution: "corretto"
          cache: maven
      - name: Clean maven
        run: mvn -ntp -U clean
      - name: "API Integration test"
        run: |
          make ci-api-client-integration
      - name: "Debug db"
        if: ${{ failure() }}
        run: docker logs api-client-integration-app-db-1
      - name: "Debug attribution"
        if: ${{ failure() }}
        run: docker logs api-client-integration-app-attribution-1
      - name: "Debug api"
        if: ${{ failure() }}
        run: docker logs api-client-integration-app-api-1
      - name: Cleanup
        if: ${{ always() }}
        run: ./scripts/cleanup-docker.sh
