name: 'DPC - Docker Build'

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      env:
        description: AWS environment to deploy to
        required: true
        type: 'string'
        default: 'dev'
      block_release_tag:
        description: Whether should block marking build as release
        type: boolean
        default: false
        required: false
    outputs:
      ecr_image_tag:
        description: "Tag for associated docker images"
        value: ${{ jobs.generate_docker_tag.outputs.docker_tag }}
      version_tag:
        description: "Tag for app version"
        value: ${{ jobs.generate_docker_tag.outputs.version_tag }}

permissions:
  id-token: write
  contents: read

env:
  VAULT_PW: ${{ secrets.VAULT_PW }}
  REPORT_COVERAGE: true
  DPC_CA_CERT: ${{ secrets.DPC_CA_CERT }}
  ENV: "github-ci"

jobs:
  generate_docker_tag:
    permissions:
      contents: read
      id-token: write
    runs-on:  >-
      codebuild-dpc-app${{
        contains(fromJSON('["prod", "sandbox"]'), inputs.env) && '-prod' || '-non-prod'
      }}-${{ github.run_id }}-${{ github.run_attempt }}
    outputs:
      version_tag: ${{ steps.get-version-tag.outputs.version_tag }}
      docker_tag: ${{ steps.output_docker_tag.outputs.docker_tag }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: "Fetch git info"
        run: |
          git fetch --quiet
      - name: "Get Version Tag"
        id: get-version-tag
        run: |
          set +e
          VERSION_TAG=`git describe --tags --exact-match`
          if [ "${{ inputs.block_release_tag }}" = true -o $? -ne 0 ]; then
            BRANCH_HASH=`git show -s --format='%h'`
            VERSION_TAG="commit_${BRANCH_HASH}"
          fi
          echo $VERSION_TAG
          echo "version_tag=$VERSION_TAG" >> "$GITHUB_OUTPUT"
          set -e
      - name: generate a tag with UTC date and GitHub run_id
        id: output_docker_tag
        run: |
          DOCKER_TAG="rls-${{ steps.get-version-tag.outputs.version_tag }}-$(date -u +'%Y%m%d%H%M')-${{ github.run_id }}"
          echo "docker_tag=$DOCKER_TAG" >> $GITHUB_OUTPUT

  docker_build_rails_apps:
    permissions:
      contents: read
      id-token: write
    runs-on: codebuild-dpc-app-non-prod-${{github.run_id}}-${{github.run_attempt}}
    strategy:
      matrix:
        app_dir: [ dpc-portal ]
        include:
          - app_dir: dpc-portal
            ecr_repository: web-portal
            make_command: make ci-portal
    steps:
      - name: Assert Ownership
        run: sudo chmod -R 777 .
      - name: "Checkout code"
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Cleanup Runner
        run: ./scripts/cleanup-docker.sh
      - name: Install docker compose manually
        run: |
          mkdir -p /usr/local/lib/docker/cli-plugins
          curl -SL https://github.com/docker/compose/releases/download/v2.32.4/docker-compose-linux-aarch64 -o /usr/local/lib/docker/cli-plugins/docker-compose
          chown root:root /usr/local/lib/docker/cli-plugins/docker-compose
          chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
      - name: "Set up Python and install Ansible"
        run: |
          sudo dnf -y install python3 python3-pip
          pip install ansible
      - name: "Set up JDK 17"
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: "17"
          distribution: "corretto"
          cache: maven
      - name: Clean maven
        run: mvn -ntp -U clean
      - name: "DPC Portal Build"
        run: |
          make ci-portal

      - name: Attribution Logs
        if: ${{ failure() }}
        run: docker logs start-v1-portals-attribution-1
