name: Dpc-Portal Accessibility Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - dpc-portal/**

jobs:
  test:
    name: 'Run Axe Accessibility tests on DPC-Portal'
    permissions:
      contents: read
      id-token: write
    runs-on: codebuild-dpc-app-non-prod-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.3.0
      - name: "Run Tests"
        run: |
          make ci-portal-accessibility
