name: "Generate and Load Golden Macaroon"

on:
  workflow_dispatch:
    inputs:
      env:
        description: AWS environment to deploy to
        required: true
        type: 'string'
        default: 'dev'
  workflow_call:
    inputs:
      env:
        description: AWS environment to generate the macaroon to
        required: true
        type: 'string'
        default: 'dev'

concurrency:
  group: generate-macaroon-for-${{ inputs.env }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  macaroon:
    name: "Get and load Golden Macaroon"
    runs-on: >-
      codebuild-dpc-app${{
        contains(fromJSON('["prod", "sandbox"]'), inputs.env) && '-prod' || '-non-prod'
      }}-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: dpc-app
      - name: AWS Credentials (non-prod)
        if: ${{ inputs.env == 'dev' || inputs.env == 'test' }}
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.NON_PROD_ACCOUNT_ID }}:role/delegatedadmin/developer/dpc-${{ inputs.env }}-github-actions
      - name: AWS Credentials (prod)
        if: ${{ inputs.env == 'sandbox' || inputs.env == 'prod' }}
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.PROD_ACCOUNT_ID }}:role/delegatedadmin/developer/dpc-${{ inputs.env }}-github-actions
      - name: Get and load Golden Macaroon
        run:  |
          ./dpc-app/scripts/generate-and-load-golden-macaroon.sh ${{ inputs.env }}
