name: Load Testing Unit Tests

on:
  pull_request:
    paths:
      - .github/workflows/load-test-unit-tests.yml
      - dpc-load-testing/**
  workflow_dispatch:

jobs:
  test:
    runs-on: codebuild-dpc-app-non-prod-${{github.run_id}}-${{github.run_attempt}}
    defaults:
      run:
        working-directory: ./dpc-load-testing
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
      - name: Install yarn
        run: npm install -g yarn
      - name: Set up tests for dpc-load-testing utilities
        run: yarn
      - name: Run ESLint
        run: yarn run lint
      - name: Run unit tests
        run: yarn test
  test-authentication-utils:
    runs-on: codebuild-dpc-app-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Test Macaroons
        run: |
          docker run --rm -v ./dpc-load-testing:/src grafana/k6 run /src/macaroonTests.js
      - name: Test JWT
        if: always()
        run: |
          docker run --rm -v ./dpc-load-testing:/src grafana/k6 run /src/jwtTests.js
