name: opt-out-import deploy

on:
  workflow_dispatch:
    inputs:
      dispatch_environment:
        description: environment
        required: false
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod
  push:
    paths:
      - .github/workflows/opt-out-import-deploy.yml
    with:
      dispatch_environment: 'dev'

jobs:
  deploy import lambda:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    env:
      INPUT_ENVIRONMENT: ${{ github.event.inputs.dispatch_environment }}
    environment: ${{ github.event.inputs.dispatch_environment }}
    steps:
      - name: 
        run: |
          echo $INPUT_ENVIRONMENT
