name: 'Tag Repo'

on:
  push:
  workflow_dispatch:
    inputs:
      repo_ref:
        description: Which branch or tag
        required: true
        default: 'main'
        type: 'string'
jobs:
  tag_repo:
    name: Tag Repository
    runs-on: ubuntu-latest
    outputs:
      next_rev: ${{ steps.set_revs.outputs.next_rev }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: "Fetch git info"
        id: set_revs
        run: |
          git fetch --quiet
          PREV_REV=`git tag -l 'r*' --sort=v:refname | tail -n 1`
          echo $PREV_REV
          PREV_REV_NUM=${PREV_REV/r}
          NEXT_REV_NUM=$((PREV_REV_NUM + 1))
          NEXT_REV=r$NEXT_REV_NUM
          echo "next_rev=$NEXT_REV" >> "$GITHUB_OUTPUT"
      - name: "Set Body"
        run: |
          BODY=`git log --pretty=format:"- %s" r46..HEAD`
          echo $BODY
      - name: Test Envs
        env:
          nr: ${{ env.NEXT_REV }}
        run: echo $nr
      - name: Release
        if: ${{ env.NEXT_REV == 'dont run' }}
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ env.BODY }}
          tag_name: ${{ env.NEXT_REV }}
          repository: ./${{ inputs.static_repo_ref }}
