name: opt-out-import deploy

on:
  workflow_dispatch:
    inputs:
      dispatch_environment:
        description: environment
        required: false
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
  push:
    paths:
      - .github/workflows/opt-out-import-deploy.yml

jobs:
  deploy_export:
    uses: ./.github/workflows/opt-out-export-dev-deploy.yml
    with:
      dispatch_environment: dev
      secrets: inherit
