name: 'Deploy Static Site'

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: Deploy where?
        required: false
        default: 'staging'
        type: choice
        options:
          - staging
          - prod
      static_repo_ref:
        description: Which branch or tag
        required: true
        default: 'main'
        type: 'string'
jobs:
  deploy_static_site:
    name: Deploy Static Site
    runs-on: self-hosted
    env:
      # Workaround until https://jira.cms.gov/browse/PLT-338 is implemented.
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"
      TARGET_BUCKET: ${{ inputs.target_environment == 'prod' && 'dpc.cms.gov' || 'stage.dpc.cms.gov' }}
      TARGET_ENV: ${{ inputs.target_environment }}
      REPO: ${{ inputs.static_repo_ref }}
    steps:
      - name: Verify inputs
        run: |
          echo $TARGET_BUCKET
          echo $TARGET_ENV
          echo $REPO
