name: opt-out-export dev deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: environment
        required: false
        default: 'dev'
  push:
    branches:
      - main
    paths:
      - lambda/opt-out-export/**
      - .github/workflows/opt-out-export-dev-deploy.yml

jobs:
  test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lambda/opt-out-export
    environment: foo
    steps:
      - name: Upload and reload
        run: env
