name: Opt-Out-Import Unit Tests

on:
  pull_request:
    paths:
      - .github/workflows/opt-out-import-unit.yml
      - lambda/opt-out-import/**
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: read
      id-token: write
    runs-on: codebuild-dpc-app-non-prod-${{github.run_id}}-${{github.run_attempt}}
    defaults:
      run:
        working-directory: ./lambda/opt-out-import
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.3.0
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: '>=1.24.4'
      - name: check go version
        run: go version
      - name: Run unit tests for opt-out-import lambda
        run: make unit-test
