name: opt-out-import deploy

on:
  workflow_dispatch:
    inputs:
      dispatch_environment:
        description: environment
        required: false
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  deploy_export:
    uses: ./.github/workflows/opt-out-export-deploy.yml@jd/mess-with-workflows
    with:
      dispatch_environment: 'dev'
