name: 'Tag Static Site'

on:
  push:
  workflow_dispatch:
    inputs:
      target_environment:
        description: Deploy where?
        required: false
        default: 'do not deploy'
        type: choice
        options:
          - 'do not deploy'
          - staging
      static_repo_ref:
        description: Which branch or tag
        required: true
        default: 'main'
        type: 'string'
jobs:
  tag_static_site:
    name: Tag Static Site
    runs-on: ubuntu-latest
    outputs:
      next_tag: ${{ steps.set_revisions.outputs.NEXT_REV }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          repository: 'CMSgov/dpc-static-site'
      - name: fetch git info
        run: |
          git fetch --quiet
      - name: set PREV and NEXT Revisions
        id: set_revisions
        run: |
          PREV_REV=`git describe --tags --abbrev=0 --match 'r*'`
          PREV_REV_NUM=${PREV_REV/r}
          NEXT_REV_NUM=$((PREV_REV_NUM + 1))
          NEXT_REV=r$NEXT_REV_NUM
          echo $NEXT_REV
     - name: build body
       run: |
         BODY=`git log --pretty=format:"- %s" $PREV_REV..HEAD`
