name: Pipefail Sanity Check

on:
  push:

permissions:
  id-token: write
  contents: read

env:
  TENV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#defaults:
#  run:
#    shell: bash

jobs:
  test-pipefail:
    runs-on: >-
      codebuild-dpc-app${{
        contains(fromJSON('["prod", "sandbox"]'), inputs.env) && '-prod' || '-non-prod'
      }}-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: AWS Credentials (non-prod)
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.NON_PROD_ACCOUNT_ID }}:role/delegatedadmin/developer/dpc-${{ inputs.env }}-github-actions
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.3.0
        with:
          repository: 'CMSgov/dpc-ops'
          ref: ${{ inputs.ops-ref }}
          ssh-key: ${{ secrets.DPC_OPS_SSH_KEY }}
          path: dpc-ops
      - name: Install Cosign to verify tenv and tofu installs
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 #v4.1.1

      - name: Install Tofu
        uses: cmsgov/cdap/actions/setup-tenv@main

      - name: Setup stdout-to-cw-logs
        uses: $/.github/actions/config-stdout-to-cw-logs

      - name: Fail inside a pipe
        run: |
          echo "Testing to see if non-zero code is swallowed"
          false | "$STDOUT_TO_CWLOGS_SCRIPT"
          echo "Should never get here"
