name: 'DPC - QuickSight Report Deploy'

on:
  workflow_dispatch:
    inputs:
      env:
        description: AWS environment to deploy to
        required: true
        type: 'string'
        default: 'dev'
      confirm_env:
        description: Double check for environment
        required: true
        type: 'string'
        default: ''
      ops-ref:
        description: Branch of dpc-ops to use
        required: false
        type: 'string'
        default: 'main'
  # for enabling dpc-ops to call, remove after quicksights lambda terraform is moved to dpc-app/
  workflow_call:
    inputs:
      env:
        description: AWS environment to deploy to
        required: true
        type: 'string'
        default: 'test'
      confirm_env:
        description: Double check for environment
        required: true
        type: 'string'
      ops-ref:
        description: Branch of dpc-ops to use
        required: false
        type: 'string'
        default: 'main'


concurrency:
  group: deploy-quicksight-report-to-${{ inputs.env }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

env:
  TENV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    name: Deploy
    permissions:
      contents: read
      id-token: write
    runs-on: >-
      codebuild-dpc-app${{
        contains(fromJSON('["prod"]'), inputs.env) && '-prod' || '-non-prod'
      }}-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Fail if not test or prod
        if: ${{ inputs.env == 'dev' || inputs.env == 'sandbox' }}
        run: |
          echo "Only run on test or prod"
          exit 1

      - name: Run and Fail if Inputs Invalid
        if: ${{ inputs.env != inputs.confirm_env }}
        run: |
          echo "Target deployment environment \"${{ inputs.env }}\" must be specified and match confirmed deployment environment \"${{ inputs.confirm_env }}\"."
          exit 1

      - name: AWS Credentials (non-prod)
        if: ${{ inputs.env == 'test' }}
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.NON_PROD_ACCOUNT_ID }}:role/delegatedadmin/developer/dpc-${{ inputs.env }}-github-actions
      - name: AWS Credentials (prod)
        if: ${{ inputs.env == 'prod' }}
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.PROD_ACCOUNT_ID }}:role/delegatedadmin/developer/dpc-${{ inputs.env }}-github-actions

      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.3.0
        with:
          repository: 'CMSgov/dpc-ops'
          ref: ${{ inputs.ops-ref }}
          ssh-key: ${{ secrets.DPC_OPS_SSH_KEY }}
          path: dpc-ops

      - name: Test and Lint Lambda Handler
        run: |
          cd dpc-ops/terraform/lambda/quicksight-reports/lambda_src
          pip install -r requirements.txt
          pytest
          pylint .

      - name: Install Cosign to verify tenv and tofu installs
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 #v4.1.1

      - name: Install Tofu
        uses: cmsgov/cdap/actions/setup-tenv@main

      - name: Verify plan
        run: |
          cd dpc-ops/terraform/lambda/quicksight-reports
          tofu init -backend-config=backends/${{ inputs.env }}.config
          tofu plan -var env=${{ inputs.env }} -out dpc-quicksight-report-release-${{ inputs.env }}.tfplan 2>&1

      - name: Apply plan
        run: |
          cd dpc-ops/terraform/lambda/quicksight-reports
          tofu apply dpc-quicksight-report-release-${{ inputs.env }}.tfplan
