name: "DPC - Test action workflow"

on:
  workflow_dispatch:

jobs:
  test-action:
    name: "Test that I can call a custom action"
    permissions:
      contents: read
      id-token: write
    runs-on: codebuild-dpc-app-non-prod-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.3.0

      - name: AWS Credentials (non-prod)
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.NON_PROD_ACCOUNT_ID }}:role/delegatedadmin/developer/dpc-dev-github-actions

      - name: Setup stdout-to-cw-logs
        uses: ./.github/actions/config-stdout-to-cw-logs

      - name: Write something to logs
        run: |
          echo "Hopefully this shows up in our logs!" | "$STDOUT_TO_CWLOGS_SCRIPT"
